export const defaultMessageContent = [
  "How about a stay in Costa Rica's lush jungle?",
  "The Himalayas are nice this time of year.",
  "What about a trip to the Mediterranean?",
  "The Galapagos are full of unique wildlife.",
  "The Appalachians hide lovely mountain towns.",
  "Iceland's northern lights are simply magical.",
  "The Great Barrier Reef is calling your name.",
  "Explore the mysteries of the Amazon rainforest.",
  "Experience the ancient wonders of Kyoto.",
  "Paris is always a good idea, isn't it?",
  "Morocco's markets are a feast for the senses.",
  "Discover the hidden gems of old Havana.",
  "Walk the cobblestone streets of Prague.",
  "Explore the temples of Angkor Wat.",
  "The markets of Istanbul await your visit, my friend.",
  "Feel the rhythm of Rio de Janeiro.",
  "New Zealand's fjords are an adventurer's dream.",
  "Trek through Patagonia's untamed wilderness.",
  "Safari through Tanzania's Serengeti Plains.",
  "Dive into the crystal waters of the Maldives.",
  "Hike the breathtaking trails of Banff.",
  "Experience the majesty of the Norwegian fjords.",
  "Discover the hidden beaches of Thailand.",
  "Explore Vietnam's stunning Ha Long Bay.",
  "Find tranquility in Bhutan's mountain monasteries.",
  "Wander through Croatia's lavender fields.",
  "Discover the quiet beauty of Slovenia's lakes.",
  "Experience the magic of Myanmar's temples.",
  "Explore Colombia's coffee country.",
  "Trek through Nepal's remote villages.",
  "Find peace in Tuscany's rolling hills.",
  "Discover the wild beauty of Scotland's Highlands.",
];
